# Generated by Django 5.2 on 2025-04-09 05:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
    ]
